title: The Rijesh Augustine Blog!
description: > # this means to ignore newlines until "baseurl:"
  A blog where I detail some fun projects.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Rijesh Augustine # add your name
author-img: avatar.jpg # add your photo
about-author: I keep bees and fly RC airplanes. I occasionaly take photos too. Currently im in a Masters program @ the University of Alberta and working with Radar. Interests include astrophotography, functional programming and STEM education.
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: # add your Github handle
linkedin: # add your Linkedin handle
#email: # add your Email address

# Disqus
discus-identifier: rijesha # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
